//! Build script for RCF Payloads
//!
//! Assembles shellcode from .asm files if nasm is available.
//! Falls back to placeholder bytes if nasm is not found.

use std::path::Path;
use std::process::Command;

fn assemble_asm(asm_name: &str, out_dir: &str) -> Option<Vec<u8>> {
    let src_path = format!("src/{}", asm_name);
    let out_path = format!("{}/{}.bin", out_dir, asm_name.trim_end_matches(".asm"));

    let status = Command::new("nasm")
        .args(["-f", "bin", &src_path, "-o", &out_path])
        .status()
        .ok()?;

    if status.success() {
        std::fs::read(&out_path).ok()
    } else {
        None
    }
}

fn generate_rust_const(name: &str, bytes: &[u8]) -> String {
    let byte_list: Vec<String> = bytes.iter().map(|b| format!("0x{:02x}", b)).collect();
    format!(
        "// Auto-generated by build.rs — {} bytes\n\
         pub const {}: &[u8] = &[\n    {}\n];\n",
        bytes.len(),
        name,
        byte_list
            .chunks(16)
            .map(|chunk| chunk.join(", "))
            .collect::<Vec<_>>()
            .join(",\n    ")
    )
}

fn main() {
    println!("cargo:rerun-if-changed=src/stager_linux_x64.asm");
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = match std::env::var("OUT_DIR") {
        Ok(dir) => dir,
        Err(e) => {
            eprintln!("cargo:warning=Failed to get OUT_DIR: {}", e);
            return;
        }
    };
    let dest_path = Path::new(&out_dir).join("shellcode.rs");

    let has_nasm = Command::new("nasm")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);

    let mut rust_code = String::new();

    if has_nasm {
        // Assemble Linux stager
        if let Some(bytes) = assemble_asm("stager_linux_x64.asm", &out_dir) {
            rust_code.push_str(&generate_rust_const("STAGER_LINUX_X64", &bytes));
            println!(
                "cargo:warning=Assembled Linux x64 stager shellcode ({} bytes)",
                bytes.len()
            );
        } else {
            rust_code.push_str("pub const STAGER_LINUX_X64: &[u8] = &[0x48, 0x31, 0xc0, 0xc3];\n");
        }
    } else {
        // Fallback: placeholders
        rust_code.push_str("// WARNING: nasm not found — using placeholder shellcode.\n");
        rust_code.push_str("// Install nasm and rebuild for real shellcode:\n");
        rust_code.push_str("//   apt install nasm         (Ubuntu/Debian)\n\n");
        rust_code.push_str("pub const STAGER_LINUX_X64: &[u8] = &[0x48, 0x31, 0xc0, 0xc3];\n");
        println!(
            "cargo:warning=nasm not found — using placeholder shellcode. Install nasm and rebuild."
        );
    }

    if let Err(e) = std::fs::write(&dest_path, rust_code) {
        eprintln!("cargo:warning=Failed to write shellcode.rs: {}", e);
        eprintln!("cargo:warning=Build may fail due to missing generated code.");
    }
}
